### PR TITLE
Fix signal in handler always aborted in HTTP/1.1

### LINKED ISSUE #1025: Requests appear aborted before handler over HTTP/1.1
**Describe the bug**

The signal `request.signal` on a `UniversalServerRequest` is aborted as soon as the request body has been read, at least over HTTP/1.1.  As a result, for most rpc handlers the request appears aborted before the handler begins (since the request has already been read).  Ideally the signal would not be aborted until the underlying connection closes.

**To Reproduce**

Create an rpc handler using node HTTP/1.1, hit the endpoint with a POST request, and read `request.signal.aborted` at the top of the handler.  It will appear aborted (i.e. take the value `true`) even though the client and server maintain a connection, and the client will be able to receive the response.

**Environment (please complete the following information):**
- @connectrpc/connect-node version: on latest `1.3.0`, likely going back further as well.
- Node.js version: v16+

**Additional context**

The issue most likely goes back to this change in node v16 https://github.com/nodejs/node/issues/40775, where the `'close'` event on an `IncomingMessage` indicates that you've read the whole message, whereas in the past it represented the resource underlying the request (i.e. would not close until the request/response flow ended, either due to actions taken by the server or client).  I believe the more straightforward fix may be to use the node [response object's `'close'` event](https://nodejs.org/api/http.html#event-close_2) rather than the request object's here: https://github.com/connectrpc/connect-es/blob/fa7726b598391b8dfd0e9f14e27dcc87aca74146/packages/connect-node/src/node-universal-handler.ts#L120-L121

### PR DESCRIPTION
**Pull request by srikrsna-buf**
Fix signal in handler always aborted in HTTP/1.1. Closes #1025.

### CODE REVIEW

File: packages/connect-node/src/node-universal-handler.ts [hunk 1]
```diff
@@ -66,69 +66,41 @@ export type NodeServerResponse = (
 };
 
 /**
- * Converts a UniversalServerRequest to a Node.js server request.
+ * Converts a Node.js server response to a UniversalServerRequest.
  * This function helps to implement adapters to server frameworks running
  * on Node.js. Please be careful using this function in your own code, as we
  * may have to make changes to it in the future.
  */
+export function universalRequestFromNodeResponse(
```
Comment (timostamm) [inline packages/connect-node/src/node-universal-handler.ts:74]: There are two relevant exports:
- universalRequestFromNodeRequest
- universalResponseToNodeResponse

IMO the most simple solution is to keep function names, and simply add an argument to universalRequestFromNodeRequest.

We can use an override for BC in v1:

```ts
export function universalRequestFromNodeRequest(
  nodeRequest: NodeServerRequest,
  nodeResponse: NodeServerResponse,
  parsedJsonBody: JsonValue | undefined,
  contextValues: ContextValues | undefined,
): UniversalServerRequest;
/**
 * @deprecated
 */
export function universalRequestFromNodeRequest(
  nodeRequest: NodeServerRequest,
  parsedJsonBody: JsonValue | undefined,
  contextValues: ContextValues | undefined,
): UniversalServerRequest;
export function universalRequestFromNodeRequest(
  nodeRequest: NodeServerRequest,
  ...rest: [  nodeResponse: NodeServerResponse,
    parsedJsonBody: JsonValue | undefined,
    contextValues: ContextValues | undefined,
  ] | [
    parsedJsonBody: JsonValue | undefined,
    contextValues: ContextValues | undefined,
  ],
): UniversalServerRequest {
  const nodeResponse: NodeServerResponse | undefined = rest.length === 3 ? rest[0] : undefined;
  const parsedJsonBody: JsonValue | undefined = (rest.length === 3 ? rest[1] : rest[0]);
  const contextValues: ContextValues | undefined = (rest.length === 3 ? rest[2] : rest[1]);
  // ...
  (nodeResponse ?? nodeRequest).once("close", onH1Close);
```

And then drop the deprecated part in v2.

**Review by timostamm — APPROVED** [review]
